version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    container_name: frontend