version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./backend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    container_name: backend
